const travel_hotels = [
  {
    name: "Le Méridien Ile Maurice",
    address: "Village Hall Lane, Pointe Aux Piments, Mauritius 21304",
    rating: 5,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Spa",
      "Tennis court",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/1d/6c/c2/aerial-view.jpg?w=1000&h=-1&s=1",
    ],
    room_types: ["Ocean view", "Suites", "Family rooms"],
    price_per_room: 4400,
    dineIncluded: true,
    location: "Mauritius",
  },
  {
    name: "The Westin Turtle Bay Resort & Spa",
    address: "Turtle Bay,Balaclava,Maurititus 21307",
    rating: 4,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/7e/fb/1c/arrival-experience.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Ocean view", "Suites", "Family rooms"],
    price_per_room: 3400,
    dineIncluded: true,
    location: "Mauritius",
  },
  {
    name: "Constance Belle Mare Plage",
    address: "Poste De Flacq, Belle Mare, Mauritius 742CU001",
    rating: 5,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/55/5a/ca/this-is-one-of-the-lounge.jpg?w=1100&h=-1&s=1",
    ],
    room_types: ["Ocean view", "Bridal suite", "Suites", "Family rooms"],
    price_per_room: 2400,
    dineIncluded: true,
    location: "Mauritius",
  },
  {
    name: "Salt Of Palmar",
    address: "Coastal Road, Palmar, Mauritius 41604",
    rating: 5,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Boating",
      "Walking tours",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1e/9a/52/29/barlounge.jpg?w=1000&h=-1&s=1",
    ],
    room_types: ["Ocean view", "Bridal suite", "Suites", "Family rooms"],
    price_per_room: 2700,
    dineIncluded: true,
    location: "Mauritius",
  },
  {
    name: "Club Med La Plantation d'Albion",
    address:
      "Avenue du Club Med, Albion, MauritiusAvenue du Club Med, Albion, Mauritius",
    rating: 4,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Boating",
      "Walking tours",
      "Babysitting",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/d4/79/4f/club-med-la-plantation.jpg?w=1000&h=-1&s=1",
    ],
    room_types: ["Ocean view", "Bridal suite", "Suites", "Family rooms"],
    price_per_room: 2700,
    dineIncluded: true,
    location: "Mauritius",
  },
  {
    name: "JW Marriott Goa",
    address: "Vagator Beach Road, Bardez 403509 India",
    rating: 4,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/28/60/38/00/jw-marriott-goa-vagator.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Ocean view", "Suites"],
    price_per_room: 3000,
    dineIncluded: true,
    location: "Goa",
  },
  {
    name: "Taj Resort & Convention Centre",
    address: "Vainguinim Beach, Dona Paula, Panjim 403004 India",
    rating: 5,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/1d/96/92/taj-hotel-convention.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Ocean view", "Suites", "City view"],
    price_per_room: 3400,
    dineIncluded: true,
    location: "Goa",
  },
  {
    name: "Zone Connect, Goa, Calangute",
    address:
      "H No 2/16A, Naika Vaddo (near St. Alex Church), Calangute 403516 India",
    rating: 4,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/23/94/22/66/zone-connect-goa-calangute.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Ocean view", "Suites", "Mountain view"],
    price_per_room: 2400,
    dineIncluded: true,
    location: "Goa",
  },
  {
    name: "La Grace Resort",
    address: "Vaswaddo Vaddy Beach, Benaulim 403716 India",
    rating: 3,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Free breakfast",
      "Beach",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/08/4f/d5/la-grace-resort.jpg?w=600&h=-1&s=1",
    ],
    room_types: ["Family Rooms"],
    price_per_room: 2600,
    dineIncluded: true,
    location: "Goa",
  },
  {
    name: "Bloom Hotel - Calangute",
    address:
      "197/37, Calangute - Baga Road Umta Vaddo, Behind McDonalds Restaurant, Calangute 403516 India",
    rating: 5,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "24-hour security",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/e9/2f/b9/bloom-hotel-calangute.jpg?w=1000&h=-1&s=1",
    ],
    room_types: ["Family Rooms", "Suites"],
    price_per_room: 3000,
    dineIncluded: true,
    location: "Goa",
  },
  {
    name: "The Lalit Grand Palace Srinagar",
    address: "Gupkar Road, Srinagar 190001 India",
    rating: 4,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/e7/9b/d0/photo0jpg.jpg?w=1000&h=-1&s=1",
    ],
    room_types: ["Bridal Suites", "Suites", "Family Rooms"],
    price_per_room: 3000,
    dineIncluded: true,
    location: "Kashmir",
  },
  {
    name: "Hotel Heevan Pahalgam",
    address: "Aru Road, Pahalgam 192126 India",
    rating: 4,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/1b/8e/82/first-look-from-the-bridge.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Bridal Suites", "Suites", "Family Rooms"],
    price_per_room: 3000,
    dineIncluded: true,
    location: "Kashmir",
  },
  {
    name: "Vivanta Dal View",
    address: "Kralsangri Brein, Srinagar 191121 India",
    rating: 5,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/e3/3d/0e/main-building.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Bridal Suites", "Suites", "Family Rooms"],
    price_per_room: 3400,
    dineIncluded: true,
    location: "Kashmir",
  },
  {
    name: "Hotel Hilltop",
    address: "Gandola Rd., Gulmarg 193403 India",
    rating: 3,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/cc/ad/58/caption.jpg?w=1100&h=-1&s=1",
    ],
    room_types: ["Bridal Suites", "Suites", "Family Rooms"],
    price_per_room: 3400,
    dineIncluded: true,
    location: "Kashmir",
  },
  {
    name: "THE OMNIA HOTEL",
    address: "Auf dem Fels, Zermatt 3920 Switzerland",
    rating: 4,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/37/72/6d/exterior-night.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Bridal Suites", "Suites", "Family Rooms"],
    price_per_room: 6400,
    dineIncluded: true,
    location: "Switzerland",
  },
  {
    name: "Hotel Belvedere Grindelwald",
    address: "Dorfstrasse 53, Grindelwald 3818 Switzerland",
    rating: 5,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1d/3a/44/07/terrasse-im-sommer-terrasse.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Bridal Suites", "Suites", "Family Rooms"],
    price_per_room: 8400,
    dineIncluded: true,
    location: "Switzerland",
  },
  {
    name: "Hotel Schweizerhof Zurich",
    address: "Bahnhofplatz 7, Zurich 8001 Switzerland",
    rating: 3,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/65/c1/7b/exterior-at-hotel-schweizerhof.jpg?w=1100&h=-1&s=1",
    ],
    room_types: ["Bridal Suites", "Suites", "Family Rooms"],
    price_per_room: 5400,
    dineIncluded: true,
    location: "Switzerland",
  },
  {
    name: "Hotel des Balances",
    address: "Weinmarkt, Lucerne 6004 Switzerland",
    rating: 4,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/49/28/80/view-from-the-room.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Bridal Suites", "Ocean View", "Suites", "Family Rooms"],
    price_per_room: 8400,
    dineIncluded: true,
    location: "Switzerland",
  },
  {
    name: "Sun Siyam Iru Fushi Maldives",
    address: "02036 Maldives",
    rating: 5,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/f4/5f/d4/sun-siyam-iru-fushi-maldives.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Bridal Suites", "Ocean View", "Suites", "Family Rooms"],
    price_per_room: 12000,
    dineIncluded: true,
    location: "Maldives",
  },
  {
    name: "Villa Nautica",
    address: "Paradise Island Resort & Spa, 08420",
    rating: 4,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/28/b5/b2/c8/wavy-navy-kids-club.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Ocean View", "Suites", "Family Rooms"],
    price_per_room: 10200,
    dineIncluded: true,
    location: "Maldives",
  },
  {
    name: "Meeru Island Resort & Spa",
    address: "20187 Maldives",
    rating: 3,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/10/0a/5f/jacuzzi-water-villas.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Ocean View", "Suites", "Family Rooms"],
    price_per_room: 8500,
    dineIncluded: true,
    location: "Maldives",
  },
  {
    name: "Hurawalhi Island Resort",
    address: "20187 Maldives",
    rating: 5,
    facilities: [
      "Free parking",
      "Free High Speed Internet (WiFi)",
      "Pool",
      "Fitness Centre with Gym / Workout Room",
      "Free breakfast",
      "Beach",
      "Bar / lounge",
      "Bowling",
      "Game room",
      "Kids stay free",
    ],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/91/a8/cc/hurawalhi-58-undersea.jpg?w=1200&h=-1&s=1",
    ],
    room_types: ["Ocean View", "Suites"],
    price_per_room: 14000,
    dineIncluded: true,
    location: "Maldives",
  },
];

export const hotelsAPI = [...travel_hotels];
