export const transports = [
  {
    vehicle: "SUV",
    type: "Private",
    fuel_type: "Diesel",
    seat: 7,
    description: "Pickup from airport",
    price: 2000,
  },
  {
    vehicle: "MPV",
    type: "Private",
    fuel_type: "EV",
    seat: 8,
    description: "Pickup from airport",
    price: 3000,
  },
  ,
  {
    vehicle: "Sedan",
    type: "Private",
    fuel_type: "EV",
    seat: 4,
    description: "Pickup from airport",
    price: 1000,
  },
  {
    vehicle: "Wagon",
    type: "Private",
    fuel_type: "EV",
    seat: 6,
    description: "Pickup from airport",
    price: 1000,
  },
  {
    vehicle: "Wagon",
    type: "Private",
    fuel_type: "Diesel",
    seat: 6,
    description: "Pickup from airport",
    price: 2000,
  },
];
